spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xqnode/springcloud-demos
          search-paths: /config/respo
          default-label: master
          username: xqnode
          password: xq1993916.