spring:
  datasource:
    url: jdbc:mysql://localhost/config_cloud?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    config:
      profile: jdbc
      server:
        jdbc:
          sql: SELECT `KEY`, `VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?   #KEY为mysql关键字，在mysql需要使用反引号来表示其为字段