spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xqnode/springcloud-study
          search-paths: /config/respo
          default-label: master
          username: xqnode
          password: xq1993916
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://xqnode:123@106.54.198.61:8761/eureka/