server:
  port: 8001
spring:
  application:
    name: eureka-client
    # rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#配置中心
  cloud:
    config:
      uri: http://localhost:8888/
      profile: default
      label: master
      name: shop
eureka:
  client:
    service-url:
      defaultZone: http://xqnode:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

