server:
  port: 8100
spring:
  application:
    name: feign-service
eureka:
  client:
    service-url:
      defaultZone: http://xqnode:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#打开feign自带的断路器
feign:
  okhttp:          #使用okhttp调用
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000 #连接超时
        readTimeout: 60000 #读取超时

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false   #禁用hystrix超时时间
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#ribbon:
#  connectTimeout: 5000
#  readTimeout: 30000
logging:
  level:
    com.xqnode.cloud.feign.MyFeignClient: debug
