server:
  port: 8200
spring:
  application:
    name: ribbon-service
eureka:
  client:
    service-url:
      defaultZone: http://xqnode:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  connectTimeout: 5000
  readTimeout: 30000

#服务监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
